imports:
    - { resource: services.yml }

parameters:
    nazka_location.province.repository.class: Doctrine\ORM\EntityRepository
    nazka_location.country.repository.class: Doctrine\ORM\EntityRepository
    nazka_location.province.class: Nazka\LocationBundle\Entity\Province
    nazka_location.country.class: Nazka\LocationBundle\Entity\Country

services:
    #Repositories
    nazka_location.province.repository:
        class:           %nazka_location.province.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - %nazka_location.province.class%

    nazka_location.country.repository:
        class:           %nazka_location.country.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - %nazka_location.country.class%
