imports:
    - { resource: admin.yml }

parameters:
#    nazka_location.example.class: Nazka\LocationBundle\Example

services:
#    nazka_location.example:
#        class: %nazka_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
